import { Language } from '../../types';

// prettier-ignore
const games = [
  ['15puzzle', require('bundle-text:../../../../games/rbg/15puzzle.rbg'), Language.rbg],
  ['Alquerque', require('bundle-text:../../../../games/rbg/alquerque.rbg'), Language.rbg],
  ['Alquerque (bad)', require('bundle-text:../../../../games/rbg/alquerque_bad.rbg'), Language.rbg],
  ['Alquerque (no capturing sequences)', require('bundle-text:../../../../games/rbg/alquerque_noCapturingSequences.rbg'), Language.rbg],
  ['Alquerque (split)', require('bundle-text:../../../../games/rbg/alquerque_split.rbg'), Language.rbg],
  ['Amazons', require('bundle-text:../../../../games/hrg/amazons.hrg'), Language.hrg],
  ['Amazons', require('bundle-text:../../../../games/kif/amazons.kif'), Language.gdl],
  ['Amazons', require('bundle-text:../../../../games/rbg/amazons.rbg'), Language.rbg],
  ['Amazons (split 2)', require('bundle-text:../../../../games/hrg/amazons_split2.hrg'), Language.hrg],
  ['Amazons (split 2)', require('bundle-text:../../../../games/rbg/amazons_split2.rbg'), Language.rbg],
  ['Amazons (split 2a)', require('bundle-text:../../../../games/rbg/amazons_split2a.rbg'), Language.rbg],
  ['Amazons (split 3)', require('bundle-text:../../../../games/rbg/amazons_split3.rbg'), Language.rbg],
  ['Amazons (split 5)', require('bundle-text:../../../../games/rbg/amazons_split5.rbg'), Language.rbg],
  ['Amazons (split 5plus)', require('bundle-text:../../../../games/rbg/amazons_split5plus.rbg'), Language.rbg],
  ['Arimaa', require('bundle-text:../../../../games/rbg/arimaa.rbg'), Language.rbg],
  ['Arimaa (fixed position)', require('bundle-text:../../../../games/rbg/arimaa_fixedPosition.rbg'), Language.rbg],
  ['Arimaa (split)', require('bundle-text:../../../../games/rbg/arimaa_split.rbg'), Language.rbg],
  ['Ataxx', require('bundle-text:../../../../games/hrg/ataxx.hrg'), Language.hrg],
  ['Backgammon', require('bundle-text:../../../../games/hrg/backgammon.hrg'), Language.hrg],
  ['Battleships', require('bundle-text:../../../../games/hrg/battleships.hrg'), Language.hrg],
  ['Bombardment', require('bundle-text:../../../../games/hrg/bombardment.hrg'), Language.hrg],
  ['Breakthrough', require('bundle-text:../../../../games/hrg/breakthrough.hrg'), Language.hrg],
  ['Breakthrough', require('bundle-text:../../../../games/kif/breakthrough.kif'), Language.gdl],
  ['Breakthrough', require('bundle-text:../../../../games/rbg/breakthrough.rbg'), Language.rbg],
  ['Breakthrough', require('bundle-text:../../../../games/rg/breakthrough.rg'), Language.rg],
  ['Breakthrough (5x5)', require('bundle-text:../../../../games/rbg/breakthrough_5x5.rbg'), Language.rbg],
  ['Breakthrough (6x6)', require('bundle-text:../../../../games/rbg/breakthrough_6x6.rbg'), Language.rbg],
  ['Breakthrough (7x7)', require('bundle-text:../../../../games/rbg/breakthrough_7x7.rbg'), Language.rbg],
  ['Breakthrough (9x9)', require('bundle-text:../../../../games/rbg/breakthrough_9x9.rbg'), Language.rbg],
  ['Breakthrough (10x10)', require('bundle-text:../../../../games/rbg/breakthrough_10x10.rbg'), Language.rbg],
  ['Breakthrough (11x11)', require('bundle-text:../../../../games/rbg/breakthrough_11x11.rbg'), Language.rbg],
  ['Breakthrough (12x12)', require('bundle-text:../../../../games/rbg/breakthrough_12x12.rbg'), Language.rbg],
  ['Breakthrough (simple)', require('bundle-text:../../../../games/rg/breakthrough-simple.rg'), Language.rg],
  ['Breakthrough (split)', require('bundle-text:../../../../games/rbg/breakthrough_split.rbg'), Language.rbg],
  ['Breakthru', require('bundle-text:../../../../games/rbg/breakthru.rbg'), Language.rbg],
  ['Breakthru (split)', require('bundle-text:../../../../games/rbg/breakthru_split.rbg'), Language.rbg],
  ['Canadian Draughts', require('bundle-text:../../../../games/rbg/canadianDraughts.rbg'), Language.rbg],
  ['Chess', require('bundle-text:../../../../games/hrg/chess.hrg'), Language.hrg],
  ['Chess', require('bundle-text:../../../../games/rbg/chess.rbg'), Language.rbg],
  ['Chess (200)', require('bundle-text:../../../../games/rbg/chess_200.rbg'), Language.rbg],
  ['Chess (king capture)', require('bundle-text:../../../../games/rbg/chess_kingCapture.rbg'), Language.rbg],
  ['Chess (king capture, 200)', require('bundle-text:../../../../games/rbg/chess_kingCapture_200.rbg'), Language.rbg],
  ['Chess Cylinder', require('bundle-text:../../../../games/rbg/chessCylinder.rbg'), Language.rbg],
  ['Chess Cylinder (king capture)', require('bundle-text:../../../../games/rbg/chessCylinder_kingCapture.rbg'), Language.rbg],
  ['Chess Gardner (5x5, king capture)', require('bundle-text:../../../../games/rbg/chessGardner5x5_kingCapture.rbg'), Language.rbg],
  ['Chess Los Alamos (6x6, king capture)', require('bundle-text:../../../../games/rbg/chessLosAlamos6x6_kingCapture.rbg'), Language.rbg],
  ['Chess Quick (5x6, king capture)', require('bundle-text:../../../../games/rbg/chessQuick5x6_kingCapture.rbg'), Language.rbg],
  ['Chess Silverman (4x5, king capture)', require('bundle-text:../../../../games/rbg/chessSilverman4x5_kingCapture.rbg'), Language.rbg],
  ['Chinese Checkers 6', require('bundle-text:../../../../games/rbg/chineseCheckers6.rbg'), Language.rbg],
  ['Clobber', require('bundle-text:../../../../games/hrg/clobber.hrg'), Language.hrg],
  ['Connect Four', require('bundle-text:../../../../games/hrg/connect4.hrg'), Language.hrg],
  ['Connect Four', require('bundle-text:../../../../games/kif/connect4.kif'), Language.gdl],
  ['Connect Four', require('bundle-text:../../../../games/rbg/connect4.rbg'), Language.rbg],
  ['Connect 6', require('bundle-text:../../../../games/rbg/connect6.rbg'), Language.rbg],
  ['Connect 6 (split)', require('bundle-text:../../../../games/rbg/connect6_split.rbg'), Language.rbg],
  ['Dice Throw (compare)', require('bundle-text:../../../../games/hrg/diceThrowCompare.hrg'), Language.hrg],
  ['Dice Throw (guess)', require('bundle-text:../../../../games/hrg/diceThrowGuess.hrg'), Language.hrg],
  ['Dots and Boxes', require('bundle-text:../../../../games/hrg/dotsAndBoxes.hrg'), Language.hrg],
  ['Double Chess', require('bundle-text:../../../../games/rbg/doubleChess.rbg'), Language.rbg],
  ['English Draughts', require('bundle-text:../../../../games/hrg/englishDraughts.hrg'), Language.hrg],
  ['English Draughts', require('bundle-text:../../../../games/rbg/englishDraughts.rbg'), Language.rbg],
  ['English Draughts (split)', require('bundle-text:../../../../games/rbg/englishDraughts_split.rbg'), Language.rbg],
  ['Fox and Geese', require('bundle-text:../../../../games/hrg/foxAndGeese.hrg'), Language.hrg],
  ['Fox and Hounds', require('bundle-text:../../../../games/rbg/foxAndHounds.rbg'), Language.rbg],
  ['Fox and Hounds (10x10)', require('bundle-text:../../../../games/rbg/foxAndHounds-10x10.rbg'), Language.rbg],
  ['Fox and Hounds (12x12)', require('bundle-text:../../../../games/rbg/foxAndHounds-12x12.rbg'), Language.rbg],
  ['Gess', require('bundle-text:../../../../games/rbg/gess.rbg'), Language.rbg],
  ['Go', require('bundle-text:../../../../games/rbg/go.rbg'), Language.rbg],
  ['Go (constsum)', require('bundle-text:../../../../games/rbg/go_constsum.rbg'), Language.rbg],
  ['Go (nopass)', require('bundle-text:../../../../games/rbg/go_nopass.rbg'), Language.rbg],
  ['Gomoku (freestyle)', require('bundle-text:../../../../games/hrg/gomoku_freeStyle.hrg'), Language.hrg],
  ['Gomoku (freestyle)', require('bundle-text:../../../../games/rbg/gomoku_freeStyle.rbg'), Language.rbg],
  ['Gomoku (standard)', require('bundle-text:../../../../games/hrg/gomoku_standard.hrg'), Language.hrg],
  ['Gomoku (standard)', require('bundle-text:../../../../games/rbg/gomoku_standard.rbg'), Language.rbg],
  ['Gomoku (standard, 11x11)', require('bundle-text:../../../../games/rbg/gomoku_standard_11x11.rbg'), Language.rbg],
  ['Gomoku (standard, 13x13)', require('bundle-text:../../../../games/rbg/gomoku_standard_13x13.rbg'), Language.rbg],
  ['Hex', require('bundle-text:../../../../games/kif/hex.kif'), Language.gdl],
  ['Hex', require('bundle-text:../../../../games/rbg/hex.rbg'), Language.rbg],
  ['Hex (5x5)', require('bundle-text:../../../../games/rbg/hex_5x5.rbg'), Language.rbg],
  ['Hex (6x6)', require('bundle-text:../../../../games/rbg/hex_6x6.rbg'), Language.rbg],
  ['Hex (7x7)', require('bundle-text:../../../../games/rbg/hex_7x7.rbg'), Language.rbg],
  ['Hex (8x8)', require('bundle-text:../../../../games/rbg/hex_8x8.rbg'), Language.rbg],
  ['Hex (9x9)', require('bundle-text:../../../../games/rbg/hex_9x9.rbg'), Language.rbg],
  ['Hex (10x10)', require('bundle-text:../../../../games/rbg/hex_10x10.rbg'), Language.rbg],
  ['International Draughts', require('bundle-text:../../../../games/rbg/internationalDraughts.rbg'), Language.rbg],
  ['Knightthrough', require('bundle-text:../../../../games/hrg/knightthrough.hrg'), Language.hrg],
  ['Knightthrough', require('bundle-text:../../../../games/kif/knightthrough.kif'), Language.gdl],
  ['Knightthrough', require('bundle-text:../../../../games/rbg/knightthrough.rbg'), Language.rbg],
  ['Knightthrough (split)', require('bundle-text:../../../../games/rbg/knightthrough_split.rbg'), Language.rbg],
  ['Minimal', require('bundle-text:../../../../games/rg/minimal.rg'), Language.rg],
  ['Monty Hall', require('bundle-text:../../../../games/kif/montyHall.kif'), Language.gdl],
  ['Oware', require('bundle-text:../../../../games/hrg/oware.hrg'), Language.hrg],
  ['Paper Soccer', require('bundle-text:../../../../games/rbg/paperSoccer.rbg'), Language.rbg],
  ['Pentago', require('bundle-text:../../../../games/hrg/pentago.hrg'), Language.hrg],
  ['Pentago', require('bundle-text:../../../../games/rbg/pentago.rbg'), Language.rbg],
  ['Pentago (split)', require('bundle-text:../../../../games/hrg/pentago_split.hrg'), Language.hrg],
  ['Pentago (split)', require('bundle-text:../../../../games/rbg/pentago_split.rbg'), Language.rbg],
  ['Pretwa', require('bundle-text:../../../../games/rbg/pretwa.rbg'), Language.rbg],
  ['Reversi', require('bundle-text:../../../../games/kif/reversi.kif'), Language.gdl],
  ['Reversi', require('bundle-text:../../../../games/rbg/reversi.rbg'), Language.rbg],
  ['Reversi (4x4)', require('bundle-text:../../../../games/rbg/reversi_4x4.rbg'), Language.rbg],
  ['Reversi (6x6)', require('bundle-text:../../../../games/rbg/reversi_6x6.rbg'), Language.rbg],
  ['Reversi (10x10)', require('bundle-text:../../../../games/rbg/reversi_10x10.rbg'), Language.rbg],
  ['SAT Solver', require('bundle-text:../../../../games/hrg/satSolver.hrg'), Language.hrg],
  ['Shortest Path', require('bundle-text:../../../../games/hrg/shortestPath.hrg'), Language.hrg],
  ['Skirmish', require('bundle-text:../../../../games/rbg/skirmish.rbg'), Language.rbg],
  ['Surakarta', require('bundle-text:../../../../games/rbg/surakarta.rbg'), Language.rbg],
  ['Surakarta (anysquare)', require('bundle-text:../../../../games/rbg/surakarta-anysquare.rbg'), Language.rbg],
  ['The Mill Game', require('bundle-text:../../../../games/rbg/theMillGame.rbg'), Language.rbg],
  ['The Mill Game (split)', require('bundle-text:../../../../games/rbg/theMillGame_split.rbg'), Language.rbg],
  ['Tic Tac Die', require('bundle-text:../../../../games/hrg/ticTacDie.hrg'), Language.hrg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/kif/ticTacToe.kif'), Language.gdl],
  ['Tic Tac Toe', require('bundle-text:../../../../games/hrg/ticTacToe.hrg'), Language.hrg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/rbg/ticTacToe.rbg'), Language.rbg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/rg/ticTacToe.rg'), Language.rg],
  ['Turing Machine', require('bundle-text:../../../../games/hrg/turingMachine.hrg'), Language.hrg],
  ['Twenty One', require('bundle-text:../../../../games/hrg/twentyOne.hrg'), Language.hrg],
  ['Ultimate Tic Tac Toe', require('bundle-text:../../../../games/hrg/ultimateTicTacToe.hrg'), Language.hrg],
  ['Yavalath', require('bundle-text:../../../../games/rbg/yavalath.rbg'), Language.rbg],
] as const;

export const presets = games.map(([name, source, extension]) => ({
  name: `${name}.${extension}`,
  source,
  extension,
}));
