import { Language } from '../../types';

// prettier-ignore
const games = [
  ['Alquerque', require('bundle-text:../../../../games/hrg/alquerque.hrg'), Language.hrg],
  ['Alquerque', require('bundle-text:../../../../games/rbg/alquerque.rbg'), Language.rbg],
  ['Alquerque (split)', require('bundle-text:../../../../games/rbg/alquerque_split.rbg'), Language.rbg],
  ['Amazons', require('bundle-text:../../../../games/hrg/amazons.hrg'), Language.hrg],
  ['Amazons', require('bundle-text:../../../../games/rbg/amazons.rbg'), Language.rbg],
  ['Amazons (split 2)', require('bundle-text:../../../../games/hrg/amazons_split2.hrg'), Language.hrg],
  ['Amazons (split 2)', require('bundle-text:../../../../games/rbg/amazons_split2.rbg'), Language.rbg],
  ['Ataxx', require('bundle-text:../../../../games/hrg/ataxx.hrg'), Language.hrg],
  ['Backgammon', require('bundle-text:../../../../games/hrg/backgammon.hrg'), Language.hrg],
  ['Battleships', require('bundle-text:../../../../games/hrg/battleships.hrg'), Language.hrg],
  ['Bombardment', require('bundle-text:../../../../games/hrg/bombardment.hrg'), Language.hrg],
  ['Breakthrough', require('bundle-text:../../../../games/hrg/breakthrough.hrg'), Language.hrg],
  ['Breakthrough', require('bundle-text:../../../../games/kif/breakthrough.kif'), Language.gdl],
  ['Breakthrough', require('bundle-text:../../../../games/rbg/breakthrough.rbg'), Language.rbg],
  ['Breakthrough', require('bundle-text:../../../../games/rg/breakthrough.rg'), Language.rg],
  ['Canadian Draughts', require('bundle-text:../../../../games/rbg/canadianDraughts.rbg'), Language.rbg],
  ['Chess', require('bundle-text:../../../../games/hrg/chess.hrg'), Language.hrg],
  ['Chess', require('bundle-text:../../../../games/rbg/chess.rbg'), Language.rbg],
  ['Chess (king capture)', require('bundle-text:../../../../games/rbg/chess_kingCapture.rbg'), Language.rbg],
  ['Chess Cylinder', require('bundle-text:../../../../games/rbg/chessCylinder.rbg'), Language.rbg],
  ['Chess Cylinder (king capture)', require('bundle-text:../../../../games/rbg/chessCylinder_kingCapture.rbg'), Language.rbg],
  ['Clobber', require('bundle-text:../../../../games/hrg/clobber.hrg'), Language.hrg],
  ['Connect Four', require('bundle-text:../../../../games/hrg/connect4.hrg'), Language.hrg],
  ['Connect Four', require('bundle-text:../../../../games/kif/connect4.kif'), Language.gdl],
  ['Connect Four', require('bundle-text:../../../../games/rbg/connect4.rbg'), Language.rbg],
  ['Connect 6', require('bundle-text:../../../../games/rbg/connect6.rbg'), Language.rbg],
  ['Connect 6 (split)', require('bundle-text:../../../../games/rbg/connect6_split.rbg'), Language.rbg],
  ['Dash Guti', require('bundle-text:../../../../games/rbg/dashGuti.rbg'), Language.rbg],
  ['Dice Throw (compare)', require('bundle-text:../../../../games/hrg/diceThrowCompare.hrg'), Language.hrg],
  ['Dice Throw (guess)', require('bundle-text:../../../../games/hrg/diceThrowGuess.hrg'), Language.hrg],
  ['Dots and Boxes', require('bundle-text:../../../../games/hrg/dotsAndBoxes.hrg'), Language.hrg],
  ['English Draughts', require('bundle-text:../../../../games/hrg/englishDraughts.hrg'), Language.hrg],
  ['English Draughts', require('bundle-text:../../../../games/rbg/englishDraughts.rbg'), Language.rbg],
  ['Fox and Geese', require('bundle-text:../../../../games/hrg/foxAndGeese.hrg'), Language.hrg],
  ['Fox and Hounds', require('bundle-text:../../../../games/rbg/foxAndHounds.rbg'), Language.rbg],
  ['Gol Skuish', require('bundle-text:../../../../games/rbg/golSkuish.rbg'), Language.rbg],
  ['Gomoku (standard)', require('bundle-text:../../../../games/hrg/gomoku_standard.hrg'), Language.hrg],
  ['Gomoku (standard)', require('bundle-text:../../../../games/rbg/gomoku_standard.rbg'), Language.rbg],
  ['Hex', require('bundle-text:../../../../games/kif/hex.kif'), Language.gdl],
  ['Hex', require('bundle-text:../../../../games/rbg/hex.rbg'), Language.rbg],
  ['International Draughts', require('bundle-text:../../../../games/rbg/internationalDraughts.rbg'), Language.rbg],
  ['Knightthrough', require('bundle-text:../../../../games/hrg/knightthrough.hrg'), Language.hrg],
  ['Knightthrough', require('bundle-text:../../../../games/kif/knightthrough.kif'), Language.gdl],
  ['Knightthrough', require('bundle-text:../../../../games/rbg/knightthrough.rbg'), Language.rbg],
  ['Knightthrough (split)', require('bundle-text:../../../../games/rbg/knightthrough_split.rbg'), Language.rbg],
  ['Lau Kata Kati', require('bundle-text:../../../../games/rbg/lauKataKati.rbg'), Language.rbg],
  ['Minimal', require('bundle-text:../../../../games/rg/minimal.rg'), Language.rg],
  ['Monty Hall', require('bundle-text:../../../../games/kif/montyHall.kif'), Language.gdl],
  ['Oware', require('bundle-text:../../../../games/hrg/oware.hrg'), Language.hrg],
  ['Pentago', require('bundle-text:../../../../games/hrg/pentago.hrg'), Language.hrg],
  ['Pentago', require('bundle-text:../../../../games/rbg/pentago.rbg'), Language.rbg],
  ['Pentago (split)', require('bundle-text:../../../../games/hrg/pentago_split.hrg'), Language.hrg],
  ['Pentago (split)', require('bundle-text:../../../../games/rbg/pentago_split.rbg'), Language.rbg],
  ['Pretwa', require('bundle-text:../../../../games/rbg/pretwa.rbg'), Language.rbg],
  ['Reversi', require('bundle-text:../../../../games/kif/reversi.kif'), Language.gdl],
  ['Reversi', require('bundle-text:../../../../games/rbg/reversi.rbg'), Language.rbg],
  ['SAT Solver', require('bundle-text:../../../../games/hrg/satSolver.hrg'), Language.hrg],
  ['Shortest Path', require('bundle-text:../../../../games/hrg/shortestPath.hrg'), Language.hrg],
  ['Skirmish', require('bundle-text:../../../../games/rbg/skirmish.rbg'), Language.rbg],
  ['Surakarta', require('bundle-text:../../../../games/rbg/surakarta.rbg'), Language.rbg],
  ['The Mill Game', require('bundle-text:../../../../games/rbg/theMillGame.rbg'), Language.rbg],
  ['The Mill Game (split)', require('bundle-text:../../../../games/rbg/theMillGame_split.rbg'), Language.rbg],
  ['Tic Tac Die', require('bundle-text:../../../../games/hrg/ticTacDie.hrg'), Language.hrg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/kif/ticTacToe.kif'), Language.gdl],
  ['Tic Tac Toe', require('bundle-text:../../../../games/hrg/ticTacToe.hrg'), Language.hrg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/rbg/ticTacToe.rbg'), Language.rbg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/rg/ticTacToe.rg'), Language.rg],
  ['Turing Machine', require('bundle-text:../../../../games/hrg/turingMachine.hrg'), Language.hrg],
  ['Twenty One', require('bundle-text:../../../../games/hrg/twentyOne.hrg'), Language.hrg],
  ['Ultimate Tic Tac Toe', require('bundle-text:../../../../games/hrg/ultimateTicTacToe.hrg'), Language.hrg],
  ['Yavalath', require('bundle-text:../../../../games/rbg/yavalath.rbg'), Language.rbg],
] as const;

export const presets = games.map(([name, source, extension]) => ({
  name: `${name}.${extension}`,
  source,
  extension,
}));
