import { Language } from '../../types';

// prettier-ignore
const games = [
  ['Ahtarah Guti (lud) #LG', require('bundle-text:../../../../games/py/hrg/ahtarahGuti_lud.hrg'), Language.hrg],
  ['Aiyawatstani (lud) #LG', require('bundle-text:../../../../games/py/hrg/aiyawatstani_lud.hrg'), Language.hrg],
  ['Alquerque', require('bundle-text:../../../../games/rbg/alquerque.rbg'), Language.rbg],
  ['Alquerque #LG', require('bundle-text:../../../../games/py/hrg/alquerque.hrg'), Language.hrg],
  ['Alquerque (lud)', require('bundle-text:../../../../games/rbg/alquerque_lud.rbg'), Language.rbg],
  ['Alquerque (lud) #LG', require('bundle-text:../../../../games/py/hrg/alquerque_lud.hrg'), Language.hrg],
  ['Amazons', require('bundle-text:../../../../games/hrg/amazons.hrg'), Language.hrg],
  ['Amazons', require('bundle-text:../../../../games/kif/amazons.kif'), Language.gdl],
  ['Amazons', require('bundle-text:../../../../games/rbg/amazons.rbg'), Language.rbg],
  ['Amazons (split 2)', require('bundle-text:../../../../games/hrg/amazons_split2.hrg'), Language.hrg],
  ['Amazons (split 2)', require('bundle-text:../../../../games/rbg/amazons_split2.rbg'), Language.rbg],
  ['Amazons (split 3)', require('bundle-text:../../../../games/hrg/amazons_split3.hrg'), Language.hrg],
  ['Amazons (split 3)', require('bundle-text:../../../../games/rbg/amazons_split3.rbg'), Language.rbg],
  ['Ataxx', require('bundle-text:../../../../games/hrg/ataxx.hrg'), Language.hrg],
  ['Backgammon', require('bundle-text:../../../../games/hrg/backgammon.hrg'), Language.hrg],
  ['Bara Guti (lud) #LG', require('bundle-text:../../../../games/py/hrg/baraGuti_lud.hrg'), Language.hrg],
  ['Bara Guti Bihar (lud) #LG', require('bundle-text:../../../../games/py/hrg/baraGutiBihar_lud.hrg'), Language.hrg],
  ['Battleships', require('bundle-text:../../../../games/hrg/battleships.hrg'), Language.hrg],
  ['Bis Gutiya (lud) #LG', require('bundle-text:../../../../games/py/hrg/bisGutiya_lud.hrg'), Language.hrg],
  ['Bombardment', require('bundle-text:../../../../games/hrg/bombardment.hrg'), Language.hrg],
  ['Breakthrough', require('bundle-text:../../../../games/hrg/breakthrough.hrg'), Language.hrg],
  ['Breakthrough', require('bundle-text:../../../../games/kif/breakthrough.kif'), Language.gdl],
  ['Breakthrough', require('bundle-text:../../../../games/rbg/breakthrough.rbg'), Language.rbg],
  ['Breakthrough', require('bundle-text:../../../../games/rg/breakthrough.rg'), Language.rg],
  ['Chalis Gutia Titagarh (lud) #LG', require('bundle-text:../../../../games/py/hrg/chalisGutiaTitagarh_lud.hrg'), Language.hrg],
  ['Chess', require('bundle-text:../../../../games/hrg/chess.hrg'), Language.hrg],
  ['Chess', require('bundle-text:../../../../games/rbg/chess.rbg'), Language.rbg],
  ['Chess (king capture)', require('bundle-text:../../../../games/hrg/chess_kingCapture.hrg'), Language.hrg],
  ['Chess (king capture)', require('bundle-text:../../../../games/rbg/chess_kingCapture.rbg'), Language.rbg],
  ['Chess Cylinder', require('bundle-text:../../../../games/rbg/chessCylinder.rbg'), Language.rbg],
  ['Chess Cylinder (king capture)', require('bundle-text:../../../../games/rbg/chessCylinder_kingCapture.rbg'), Language.rbg],
  ['Clobber', require('bundle-text:../../../../games/hrg/clobber.hrg'), Language.hrg],
  ['Connect Four', require('bundle-text:../../../../games/hrg/connect4.hrg'), Language.hrg],
  ['Connect Four', require('bundle-text:../../../../games/kif/connect4.kif'), Language.gdl],
  ['Connect Four', require('bundle-text:../../../../games/rbg/connect4.rbg'), Language.rbg],
  ['Dam Hariman (lud) #LG', require('bundle-text:../../../../games/py/hrg/damHariman_lud.hrg'), Language.hrg],
  ['Dam Singapore (lud) #LG', require('bundle-text:../../../../games/py/hrg/damSingapore_lud.hrg'), Language.hrg],
  ['Dash Guti', require('bundle-text:../../../../games/rbg/dashGuti.rbg'), Language.rbg],
  ['Dash Guti #LG', require('bundle-text:../../../../games/py/hrg/dashGuti.hrg'), Language.hrg],
  ['Dash Guti (lud) #LG', require('bundle-text:../../../../games/py/hrg/dashGuti_lud.hrg'), Language.hrg],
  ['Dice Throw (compare)', require('bundle-text:../../../../games/hrg/diceThrowCompare.hrg'), Language.hrg],
  ['Dice Throw (guess)', require('bundle-text:../../../../games/hrg/diceThrowGuess.hrg'), Language.hrg],
  ['Dots and Boxes', require('bundle-text:../../../../games/hrg/dotsAndBoxes.hrg'), Language.hrg],
  ['English Draughts', require('bundle-text:../../../../games/hrg/englishDraughts.hrg'), Language.hrg],
  ['English Draughts', require('bundle-text:../../../../games/rbg/englishDraughts.rbg'), Language.rbg],
  ['Fox and Geese', require('bundle-text:../../../../games/hrg/foxAndGeese.hrg'), Language.hrg],
  ['Fox and Geese (lud)', require('bundle-text:../../../../games/hrg/foxAndGeese_lud.hrg'), Language.hrg],
  ['Fox and Hounds', require('bundle-text:../../../../games/hrg/foxAndHounds.hrg'), Language.hrg],
  ['Fox and Hounds', require('bundle-text:../../../../games/rbg/foxAndHounds.rbg'), Language.rbg],
  ['Gol Ekuish (lud) #LG', require('bundle-text:../../../../games/py/hrg/golEkuish_lud.hrg'), Language.hrg],
  ['Gol Skuish', require('bundle-text:../../../../games/rbg/golSkuish.rbg'), Language.rbg],
  ['Gol Skuish #LG', require('bundle-text:../../../../games/py/hrg/golSkuish.hrg'), Language.hrg],
  ['Gomoku (free style)', require('bundle-text:../../../../games/hrg/gomoku_freeStyle.hrg'), Language.hrg],
  ['Gomoku (free style)', require('bundle-text:../../../../games/rbg/gomoku_freeStyle.rbg'), Language.rbg],
  ['Gomoku (standard)', require('bundle-text:../../../../games/hrg/gomoku_standard.hrg'), Language.hrg],
  ['Gomoku (standard)', require('bundle-text:../../../../games/rbg/gomoku_standard.rbg'), Language.rbg],
  ['Hewakam Keliya (lud) #LG', require('bundle-text:../../../../games/py/hrg/hewakamKeliya_lud.hrg'), Language.hrg],
  ['Hex', require('bundle-text:../../../../games/hrg/hex.hrg'), Language.hrg],
  ['Hex', require('bundle-text:../../../../games/kif/hex.kif'), Language.gdl],
  ['Hex', require('bundle-text:../../../../games/rbg/hex.rbg'), Language.rbg],
  ['Kaua Dorki (lud) #LG', require('bundle-text:../../../../games/py/hrg/kauaDorki_lud.hrg'), Language.hrg],
  ['Knightthrough', require('bundle-text:../../../../games/hrg/knightthrough.hrg'), Language.hrg],
  ['Knightthrough', require('bundle-text:../../../../games/kif/knightthrough.kif'), Language.gdl],
  ['Knightthrough', require('bundle-text:../../../../games/rbg/knightthrough.rbg'), Language.rbg],
  ['Kotu Ellima (lud) #LG', require('bundle-text:../../../../games/py/hrg/kotuEllima_lud.hrg'), Language.hrg],
  ['Lam Pusri (lud) #LG', require('bundle-text:../../../../games/py/hrg/lamPusri_lud.hrg'), Language.hrg],
  ['Lau Kata Kati', require('bundle-text:../../../../games/rbg/lauKataKati.rbg'), Language.rbg],
  ['Lau Kata Kati #LG', require('bundle-text:../../../../games/py/hrg/lauKataKati.hrg'), Language.hrg],
  ['Lau Kata Kati (lud) #LG', require('bundle-text:../../../../games/py/hrg/lauKataKati_lud.hrg'), Language.hrg],
  ['Meurimueng Rimueng Peuet Ploh (lud) #LG', require('bundle-text:../../../../games/py/hrg/meurimuengRimuengPeuetPloh_lud.hrg'), Language.hrg],
  ['Minimal', require('bundle-text:../../../../games/rg/minimal.rg'), Language.rg],
  ['Mogul Putthan (lud) #LG', require('bundle-text:../../../../games/py/hrg/mogulPutthan_lud.hrg'), Language.hrg],
  ['Monty Hall', require('bundle-text:../../../../games/kif/montyHall.kif'), Language.gdl],
  ['Oware', require('bundle-text:../../../../games/hrg/oware.hrg'), Language.hrg],
  ['Pentago', require('bundle-text:../../../../games/hrg/pentago.hrg'), Language.hrg],
  ['Pentago', require('bundle-text:../../../../games/rbg/pentago.rbg'), Language.rbg],
  ['Pentago (split)', require('bundle-text:../../../../games/hrg/pentago_split.hrg'), Language.hrg],
  ['Pentago (split)', require('bundle-text:../../../../games/rbg/pentago_split.rbg'), Language.rbg],
  ['Peralikatuma (lud) #LG', require('bundle-text:../../../../games/py/hrg/peralikatuma_lud.hrg'), Language.hrg],
  ['Pretwa', require('bundle-text:../../../../games/rbg/pretwa.rbg'), Language.rbg],
  ['Pretwa #LG', require('bundle-text:../../../../games/py/hrg/pretwa.hrg'), Language.hrg],
  ['Pretwa (lud) #LG', require('bundle-text:../../../../games/py/hrg/pretwa_lud.hrg'), Language.hrg],
  ['Ratti Chitti Bakri (lud) #LG', require('bundle-text:../../../../games/py/hrg/rattiChittiBakri_lud.hrg'), Language.hrg],
  ['Reversi', require('bundle-text:../../../../games/hrg/reversi.hrg'), Language.hrg],
  ['Reversi', require('bundle-text:../../../../games/kif/reversi.kif'), Language.gdl],
  ['Reversi', require('bundle-text:../../../../games/rbg/reversi.rbg'), Language.rbg],
  ['SAT Solver', require('bundle-text:../../../../games/hrg/satSolver.hrg'), Language.hrg],
  ['Satoel (lud) #LG', require('bundle-text:../../../../games/py/hrg/satoel_lud.hrg'), Language.hrg],
  ['Shortest Path', require('bundle-text:../../../../games/hrg/shortestPath.hrg'), Language.hrg],
  ['Skirmish', require('bundle-text:../../../../games/rbg/skirmish.rbg'), Language.rbg],
  ['Smasandyutakankarikrida (lud) #LG', require('bundle-text:../../../../games/py/hrg/smasandyutakankarikrida_lud.hrg'), Language.hrg],
  ['Surakarta', require('bundle-text:../../../../games/hrg/surakarta.hrg'), Language.hrg],
  ['Surakarta', require('bundle-text:../../../../games/rbg/surakarta.rbg'), Language.rbg],
  ['Tavelspel (lud) #LG', require('bundle-text:../../../../games/py/hrg/tavelspel_lud.hrg'), Language.hrg],
  ['Terhuchu Small (lud) #LG', require('bundle-text:../../../../games/py/hrg/terhuchuSmall_lud.hrg'), Language.hrg],
  ['The Mill Game', require('bundle-text:../../../../games/hrg/theMillGame.hrg'), Language.hrg],
  ['The Mill Game', require('bundle-text:../../../../games/rbg/theMillGame.rbg'), Language.rbg],
  ['Tic Tac Die', require('bundle-text:../../../../games/hrg/ticTacDie.hrg'), Language.hrg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/kif/ticTacToe.kif'), Language.gdl],
  ['Tic Tac Toe', require('bundle-text:../../../../games/hrg/ticTacToe.hrg'), Language.hrg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/rbg/ticTacToe.rbg'), Language.rbg],
  ['Tic Tac Toe', require('bundle-text:../../../../games/rg/ticTacToe.rg'), Language.rg],
  ['Tuknanavuhpi (lud) #LG', require('bundle-text:../../../../games/py/hrg/tuknanavuhpi_lud.hrg'), Language.hrg],
  ['Turing Machine', require('bundle-text:../../../../games/hrg/turingMachine.hrg'), Language.hrg],
  ['Twenty One', require('bundle-text:../../../../games/hrg/twentyOne.hrg'), Language.hrg],
  ['Ultimate Tic Tac Toe', require('bundle-text:../../../../games/hrg/ultimateTicTacToe.hrg'), Language.hrg],
  ['Yavalath', require('bundle-text:../../../../games/hrg/yavalath.hrg'), Language.hrg],
  ['Yavalath', require('bundle-text:../../../../games/rbg/yavalath.rbg'), Language.rbg],
] as const;

export const presets = games.map(([name, source, extension]) => ({
  name: `${name}.${extension}`,
  source,
  extension,
}));
