from lineGames import *
game = LineGame()
game.addBoardAlquerque(width=5, height=5) 
for d in[N, S]: game.attachTriangle3(dir=d, height=3)
game.addPiecesAlquerque(InitialPieces.SQUARE_2ROWS)
game.addPiecesTriangle(S, InitialPieces.TRIANGLE_FULL_NOROOT, WHITE_PIECE)
game.addPiecesTriangle(N, InitialPieces.TRIANGLE_FULL_NOROOT, BLACK_PIECE)
game.setRules(CaptureSequences.NONE, captureMandatory.NOMANDATORY)
game.setLimits(stagnation=None, maxTurns=1250)
game.printHRG()
