from lineGames import *
game = LineGame()
game.addBoardPoint()
game.attachTriangle3(dir=S, height=4)
game.attachTriangle3(dir=N, height=4)
game.addPiecesTriangle(S, InitialPieces.TRIANGLE_FULL_NOROOT, WHITE_PIECE)
game.addPiecesTriangle(N, InitialPieces.TRIANGLE_FULL_NOROOT, BLACK_PIECE)
game.addNode("nodeL", piece=WHITE_PIECE, edges={E: v(0, 0, 'c'), S: 'tsouthvy3x0', N: 'tnorthvy3x2'})
game.addNode("nodeR", piece=BLACK_PIECE, edges={W: v(0, 0, 'c'), S: 'tsouthvy3x2', N: 'tnorthvy3x0'})
game.setRules(CaptureSequences.NONE, captureMandatory.NOMANDATORY)
game.setLimits(stagnation=None, maxTurns=1250)
game.printHRG()
