from lineGames import *
game = LineGame()
game.addBoardPoint()
game.attachTriangle3(dir=S, height=4)
game.attachTriangle3(dir=N, height=4)
game.addPiecesTriangle(S, InitialPieces.TRIANGLE_FULL_NOROOT, WHITE_PIECE)
game.addPiecesTriangle(N, InitialPieces.TRIANGLE_FULL_NOROOT, BLACK_PIECE)
game.setRules(CaptureSequences.FULL, captureMandatory.MANDATORY)
game.setLimits(stagnation=100, maxTurns=None)
game.printHRG()
