name: docs
on:
  push:
    branches:
      - master
env:
  CARGO_INCREMENTAL: 0
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache-workspaces: interpreter_rust
          target: wasm32-unknown-unknown
          toolchain: 1.89.0
      - name: Install Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: npm
          cache-dependency-path: interpreter_node/package-lock.json
          node-version: 24.6.0
      - name: Install wasm-pack
        run: npm install --global wasm-pack@0.13.1
      - name: Install
        run: npm --prefix interpreter_node ci
      - name: Build `interpreter` WASM module
        run: wasm-pack build --out-dir ../../interpreter_node/src/wasm/interpreter --out-name index --target web interpreter_rust/interpreter
      - name: Build `lsp_browser` WASM module
        run: wasm-pack build --out-dir ../../interpreter_node/src/wasm/lsp --out-name index --target web interpreter_rust/lsp_browser
      - name: Build docs
        run: npm --prefix interpreter_node run build
      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          allow_empty_commit: true
          force_orphan: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./interpreter_node/lib/ui
